#!/bin/sh
cd "${0%/*}" || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/polyMesh
rm -rf constant/fluid/polyMesh
rm -rf constant/solid/polyMesh

rm -r generateAndSplit/fluidID.csv
rm -r generateAndSplit/solidID.csv

# Emptying both CSV files
>fluidID.csv
>solidID.csv

cleanCase
#------------------------------------------------------------------------------
