#!/bin/bash
# Using openfoam 7 to create mesh
source $HOME/OpenFOAM/OpenFOAM-7/etc/bashrc WM_LABEL_SIZE=64 FOAMY_HEX_MESH=yes

# Cleaning up old files
./Allclean

# Generating standard block mesh
blockMesh

# Building OpenFoam-5 points to mesh
cd simpleFoam
wclean
wmake
cd ..

# Moving files around to have the zones be assigned
# Creating solid and fluid regions
./test
cp -r fluidID.csv generateAndSplit/
cp -r solidID.csv generateAndSplit/
cd generateAndSplit/
python3 zoneIDReplace.py
cp -r cellZones ../constant/polyMesh
cd ..

# Refining the mesh # 1

rm -r 100
#cp -r 1/polyMesh constant
#rm -r 1
refineMesh -all -overwrite

#Split mesh into different surface regions
transformPoints -scale "(0.001 0.001 0.001)"
topoSet


# Split up the mesh into different physical regions
splitMeshRegions -cellZonesOnly -defaultRegionName fluid -overwrite

# Removing 100 file that should not be

