# data config for computation of metrics

## SIZE OF COMPONENTS
units:
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1
  - - 1
    - 1

## POWERS OF THE COMPONENTS
powers:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

## LENGTH OF LAYOUT BOARD
length: 0.1